---
- name: Install and configure MySQL
  hosts: localhost
  become: yes
  vars:
    mysql_root_password: "database-password"

  tasks:
    - name: Install Python3 and Pip3
      ansible.builtin.apt:
        name:
          - python3-pip
        state: present
        update_cache: yes

    - name: Install PyMySQL
      ansible.builtin.pip:
        name: pymysql
        state: present

    - name: Install MySQL Server
      ansible.builtin.apt:
        name: mysql-server
        state: present
        update_cache: yes

    - name: Ensure MySQL is running
      ansible.builtin.systemd:
        name: mysql
        state: started
        enabled: yes

    - name: Wait for MySQL to start up
      ansible.builtin.wait_for:
        port: 3306
        delay: 10  # Delay before start checking
        timeout: 30  # Timeout for connection attempt

    - name: Disable auth_socket plugin
      ansible.builtin.shell:
        cmd: |
          sudo mysql -e "ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY '{{ mysql_root_password }}';"
        warn: false

    - name: Allow remote root access
      ansible.builtin.mysql_user:
        login_user: root
        login_password: "{{ mysql_root_password }}"
        user: root
        host: '%'
        password: "{{ mysql_root_password }}"
        priv: "*.*:ALL,GRANT"
        append_privs: yes
        state: present
        encrypted: no
        plugin: mysql_native_password
        check_implicit_admin: yes

    - name: Modify MySQL configuration to allow remote connections
      ansible.builtin.lineinfile:
        path: /etc/mysql/mysql.conf.d/mysqld.cnf
        regexp: '^bind-address'
        line: 'bind-address = 0.0.0.0'
      notify:
        - Restart MySQL service

  handlers:
    - name: Restart MySQL service
      ansible.builtin.systemd:
        name: mysql
        state: restarted
        enabled: yes
